config/routes.rb
Rails.application.routes.draw do
  
  resources :presentations do
    resources :slides
  end

  root 'presentations#index'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  has_many :slides, dependent: :destroy
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :presentation
  validates :presentation, presence: true

  def get_next_slide
    slides = self.presentation.slides
    slides.each_with_index do |slide,index|
      if self == slide && !slides[index+1].nil?
        return slides[index+1]
      end
    end
    return nil
  end

  def get_previous_slide
    slides = self.presentation.slides
    return nil if self == slides.first
    slides.each_with_index do |slide,index|
      if self == slide
        return slides[index-1]
      end
    end
    return nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    if @presentation.slides.count > 0
      redirect_to "/presentations/#{@presentation.id}/slides/#{@presentation.slides.first.id}"
    else
      render 'error'
    end
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
    @slides = @presentation.slides
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to edit_presentation_path(@presentation), notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:title, :description)
    end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)
    @slide.presentation = Presentation.find(params["presentation_id"])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to edit_presentation_path(@slide.presentation)}
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    presentation = @slide.presentation
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to edit_presentation_path(presentation)}
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    presentation = @slide.presentation
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to edit_presentation_path(presentation), notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Presentloop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/presentations/_form.html.erb
<%= form_for(@presentation) do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% @presentation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

<%= render 'slides/list_slides' %>

<%= link_to 'New Slide', new_presentation_slide_path(@presentation) %>

app/views/presentations/error.html.erb
<h1>No slides in this presentation :(<h1>

app/views/presentations/index.html.erb
<h1>Listing presentations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.title %></td>
        <td><%= presentation.description %></td>
        <td><%= link_to 'Show', presentation %></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New presentation</h1>

<%= render 'form' %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @presentation.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @presentation.description %>
</p>

<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>

app/views/slides/_form.html.erb
<%= form_for(@slide, url:presentation_slides_path) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/_list_slides.html.erb
<h1>Listing slides</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
<% @slides.each do |slide| %>
    <tr>
      <td><%= slide.title %></td>
      <td><%= slide.content %></td>
      <td><%= link_to 'Edit', "/presentations/#{slide.presentation.id}/slides/#{slide.id}/edit" %></td>
      <td><%= link_to 'Destroy',"/presentations/#{slide.presentation.id}/slides/#{slide.id}" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
    </tbody>
</table>

<br>


 

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= form_for(@slide, url:"/presentations/#{@slide.presentation.id}/slides/#{@slide.id}",method: :put) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', presentation_slides_path %>

app/views/slides/index.html.erb
<%= render 'list_slides' %>

<%= link_to 'New Slide', new_presentation_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', presentation_slides_path %>

app/views/slides/show.html.erb
<h1>
  <%= @slide.title %>
</h1>

<p>
  <%= @slide.content %>
</p>
<br><hr>
<span class = "left">
<% if @slide.get_previous_slide %>
<%= link_to "Previous Slide ", "/presentations/#{@slide.presentation.id}/slides/#{@slide.get_previous_slide.id}" %>
<% end %>
</span>
<span class = "right" style="float:right">
<% if @slide.get_next_slide %>
<%= link_to "Next Slide", "/presentations/#{@slide.presentation.id}/slides/#{@slide.get_next_slide.id}" %>
<% end %>
</span>